"""add geofence col in Listings

Revision ID: 04ea1438a79a
Revises: 8c21d8729b80
Create Date: 2019-11-22 10:22:46.361750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ea1438a79a'
down_revision = '8c21d8729b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Listings', sa.Column('geofence', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Listings', 'geofence')
    # ### end Alembic commands ###
