"""empty message

Revision ID: 4cd7097f2308
Revises: 04ea1438a79a
Create Date: 2019-11-27 20:47:34.121163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd7097f2308'
down_revision = '04ea1438a79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Listings', sa.Column('commercial_units', sa.Text(), nullable=True))
    op.add_column('Listings', sa.Column('residential_units', sa.Text(), nullable=True))
    op.add_column('Listings', sa.Column('unite_principale', sa.Text(), nullable=True))
    op.add_column('Listings', sa.Column('unites_residentielles', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Listings', 'unites_residentielles')
    op.drop_column('Listings', 'unite_principale')
    op.drop_column('Listings', 'residential_units')
    op.drop_column('Listings', 'commercial_units')
    # ### end Alembic commands ###
