"""initiating db

Revision ID: 804b54c94663
Revises: 
Create Date: 2019-11-20 09:10:26.902139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804b54c94663'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('centris_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('centris_detail_url', sa.Text(), nullable=True),
    sa.Column('broker_detail_url', sa.Text(), nullable=True),
    sa.Column('lat', sa.Text(), nullable=True),
    sa.Column('lng', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('potential_revenue', sa.Integer(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Listings')
    # ### end Alembic commands ###
