"""Add Fences table

Revision ID: 8c21d8729b80
Revises: 804b54c94663
Create Date: 2019-11-22 09:36:12.422694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c21d8729b80'
down_revision = '804b54c94663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Fences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.Text(), nullable=True),
    sa.Column('coords', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Fences')
    # ### end Alembic commands ###
