"""empty message

Revision ID: a714c6a8054b
Revises: 
Create Date: 2019-11-13 20:14:31.182427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a714c6a8054b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('centris_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('centris_detail_url', sa.Text(), nullable=True),
    sa.Column('broker_detail_url', sa.Text(), nullable=True),
    sa.Column('lat', sa.Text(), nullable=True),
    sa.Column('lng', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Listings')
    # ### end Alembic commands ###
